### ISSUE TITLE
wrong first example, cplot

### ISSUE THREAD

**Issue by nschloe** [ZettZet/plotcp#6]
Your main example
```python
from plotcp import plotcp
import matplotlib.pyplot as plt

def f(z):
    return (z+1) / z

plotcp(f, (-4, 4), (-4, 4))
plt.show()
```
seems to produce wrong output. Note that `f` has a root at `z=-1` and a pole at `z=0`. None of this is seen in the plot, it's more like `+1` is a point where something happens:

![sc1](https://user-images.githubusercontent.com/181628/124138003-83677380-da86-11eb-923a-67b92c0c8263.png)

[cplot](https://github.com/nschloe/cplot), a package of mine for the same purpose, seems to get it right:

```python
import cplot

cplot.show(f, (-4, 4), (-4, 4))
```

![sc2](https://user-images.githubusercontent.com/181628/124138092-9bd78e00-da86-11eb-853e-745121171096.png)

**Comment by ZettZet** [comment]
### Hello!

Sorry for the long answer. Some things make you distracted.
I have checked your issue and I can confidently say that plotcp works correctly. The problem is that you expect a different result. 

plotcp does not give information about special points, such as poles, roots, and so on. plotcp gives a general idea of how a grid or a certain area is transformed under the action of some complex function.

Let me show you:

1. We have
![d38bdcd0a4722b2dc34e78385d93a0bc](https://user-images.githubusercontent.com/55871784/126907139-99757859-a871-43b6-b419-49dabd7795f3.png)
1. Suppose 
![0ca48d7d0d6db496899f1cb4b4132b4a](https://user-images.githubusercontent.com/55871784/126907157-25a1ba4a-3e9c-4b04-afff-9cbc6becf38b.png)
![9f1c6349e73d85a346110dcb41a10321](https://user-images.githubusercontent.com/55871784/126907165-4de70027-312b-4670-b1c5-5f25488ef664.png)
1. Multiply by complex conjugate
![c4a6023a71ea28c999f279e2c050ac24](https://user-images.githubusercontent.com/55871784/126907175-889842fd-37b6-4811-9aa9-45845b3dae04.png)
1. Take real and imaginary parts
![24050c69ed2e9be65cc91c09b0f27604](https://user-images.githubusercontent.com/55871784/126907185-8167354e-c838-4dee-8d8c-12b2a80ed88f.png)
![4ba8ef845a0ef3ecefb411636ecf3c40](https://user-images.githubusercontent.com/55871784/126907186-087c5d39-eaae-4190-b05d-7c2fd16b5493.png)
1. Go to [desmos complex map](https://www.desmos.com/calculator/ah5sro4qot) and type real and imaginary parts to they places(I did it for you).

You will see same thing that plotcp did.

We can see `z=1` is "special" in output even on first step. We have 1 plus 1/z — something litiraly small. If you plot 1/z you will see same picture, but without offset.

I hope I have made this clear to you.

**Comment by nschloe** [comment]
Are you saying that the straight lines and circles in your output plot are the images of... what?

**Comment by ZettZet** [comment]
The straight lines under the circles are the original grid, similar to the coordinate grid of the complex plane.

Circles are what these lines have become.

Remember that rational functions are a Mobius transform. They map each straight line or circle to another straight line or circle. 

`f(z)=1+1/z`, as we can see, maps each straight line of the coordinate grid into a circle.
